import { getBasePath } from './path.js';
import { ls, read, copy, mkdir, create } from './file.js';
import { search, browse, fetchPage } from './web.js';
import { listApps, openApp, closeApp } from './system.js';
import { 
  initBrowser, 
  clickElement, 
  fillField, 
  selectOption, 
  viewChanges, 
  getPageContent, 
  takeScreenshot, 
  closeBrowser,
  searchOnPage,
  findElements,
  searchOnEngine,
  downloadFile
} from './browser.js';
import { executeCode, executeFile, runJavaScript, runPython, formatCode } from './code.js';
import { 
  gitInit,
  gitClone,
  gitAdd,
  gitCommit,
  gitPush,
  gitPull,
  gitStatus,
  gitLog,
  gitBranchCreate,
  gitBranchDelete,
  gitBranchList,
  gitCheckout,
  gitCheckoutNew,
  gitMerge,
  gitDiff,
  gitRemoteAdd,
  gitRemoteList,
  gitConfigUser,
  gitReset,
  gitStash,
  gitStashPop
} from './git.js';
import {
  createTask,
  getTasks,
  getTask,
  updateTask,
  deleteTask,
  completeTask,
  splitTask,
  getTaskStats,
  clearTasks
} from './task.js';
import {
  addMemory,
  searchMemory,
  getAllMemories,
  getMemory,
  updateMemory,
  deleteMemory,
  getMemoryStats,
  getRelatedMemories,
  clearMemory
} from './memory.js';
import {
  readCSV,
  writeCSV,
  readJSON,
  writeJSON,
  csvToJSON,
  jsonToCSV,
  queryData,
  analyzeData,
  sortData
} from './data.js';
import {
  executeSQL,
  query,
  insert,
  update,
  deleteData,
  createTable,
  dropTable,
  getTables,
  getTableSchema,
  executeTransaction,
  closeDB
} from './db.js';
import {
  sendEmail,
  sendTextEmail,
  sendHtmlEmail,
  sendEmailWithAttachments,
  sendTemplateEmail,
  checkEmailConfig
} from './email.js';
import {
  getCPUInfo,
  getMemoryInfo,
  getDiskInfo,
  getNetworkInfo,
  getProcesses,
  getSystemInfo,
  getCurrentProcess,
  getSystemLoad,
  monitorSystem,
  formatBytes,
  formatUptime
} from './monitor.js';
import {
  addScheduleTask,
  removeScheduleTask,
  getScheduleTasks,
  getScheduleTask,
  updateScheduleTask,
  toggleScheduleTask,
  startScheduler,
  stopScheduler
} from './scheduler.js';
import { FileStorage, createStorage } from './storage.js';
import { ocr, ocrBatch } from './ocr.js';
import { vision, visionFromUrl } from './vision.js';
import { createPpt, createWord, createExcel, readExcel } from './office.js';
import {
  isSandboxEnabled,
  createJavaScriptSandbox,
  runJavaScriptSandbox,
  runPythonSandbox,
  executeCodeSandbox
} from './sandbox.js';
import {
  spawnAgent,
  delegateTask,
  getClusterStatus,
  stopAgent,
  stopAllAgents,
  parallelExecute,
  getAgent,
  panelDiscussion,
  pipeline,
  voting
} from './cluster.js';
import {
  loginWechat,
  logoutWechat,
  startWechatPolling,
  stopWechatPolling,
  sendWechatMessage,
  sendWechatImage,
  getWechatStatus,
  generateWechatQRCode
} from './wechat.js';

export {
  getBasePath,
  ls,
  read,
  copy,
  mkdir,
  create,
  spawnAgent,
  delegateTask,
  getClusterStatus,
  stopAgent,
  stopAllAgents,
  parallelExecute,
  getAgent,
  panelDiscussion,
  pipeline,
  voting,
  search,
  browse,
  fetchPage,
  listApps,
  openApp,
  closeApp,
  initBrowser,
  clickElement,
  fillField,
  selectOption,
  viewChanges,
  getPageContent,
  takeScreenshot,
  closeBrowser,
  searchOnPage,
  findElements,
  searchOnEngine,
  downloadFile,
  executeCode,
  executeFile,
  runJavaScript,
  runPython,
  formatCode,
  gitInit,
  gitClone,
  gitAdd,
  gitCommit,
  gitPush,
  gitPull,
  gitStatus,
  gitLog,
  gitBranchCreate,
  gitBranchDelete,
  gitBranchList,
  gitCheckout,
  gitCheckoutNew,
  gitMerge,
  gitDiff,
  gitRemoteAdd,
  gitRemoteList,
  gitConfigUser,
  gitReset,
  gitStash,
  gitStashPop,
  createTask,
  getTasks,
  getTask,
  updateTask,
  deleteTask,
  completeTask,
  splitTask,
  getTaskStats,
  clearTasks,
  addMemory,
  searchMemory,
  getAllMemories,
  getMemory,
  updateMemory,
  deleteMemory,
  getMemoryStats,
  getRelatedMemories,
  clearMemory,
  readCSV,
  writeCSV,
  readJSON,
  writeJSON,
  csvToJSON,
  jsonToCSV,
  queryData,
  analyzeData,
  sortData,
  executeSQL,
  query,
  insert,
  update,
  deleteData,
  createTable,
  dropTable,
  getTables,
  getTableSchema,
  executeTransaction,
  closeDB,
  sendEmail,
  sendTextEmail,
  sendHtmlEmail,
  sendEmailWithAttachments,
  sendTemplateEmail,
  checkEmailConfig,
  getCPUInfo,
  getMemoryInfo,
  getDiskInfo,
  getNetworkInfo,
  getProcesses,
  getSystemInfo,
  getCurrentProcess,
  getSystemLoad,
  monitorSystem,
  formatBytes,
  formatUptime,
  addScheduleTask,
  removeScheduleTask,
  getScheduleTasks,
  getScheduleTask,
  updateScheduleTask,
  toggleScheduleTask,
  startScheduler,
  stopScheduler,
  FileStorage,
  createStorage,
  isSandboxEnabled,
  createJavaScriptSandbox,
  runJavaScriptSandbox,
  runPythonSandbox,
  executeCodeSandbox,
  ocr,
  ocrBatch,
  vision,
  visionFromUrl,
  createPpt,
  createWord,
  createExcel,
  readExcel,
  loginWechat,
  logoutWechat,
  startWechatPolling,
  stopWechatPolling,
  sendWechatMessage,
  sendWechatImage,
  getWechatStatus,
  generateWechatQRCode
};

// ============================================
// 工具元数据定义（用于自动生成注册表）
// ============================================
const TOOL_METADATA = {
  // 文件操作
  ls: { argCount: 1 },
  read: { argCount: 1 },
  copy: { argCount: 2 },
  mkdir: { argCount: 1 },
  create: { argCount: 2, customArgs: true },

  // 网络
  search: { argCount: 1, customArgs: true },
  browse: { argCount: 1 },
  fetchPage: { argCount: 1 },

  // 系统
  listApps: { argCount: 0 },
  openApp: { argCount: 1 },
  closeApp: { argCount: 1 },

  // 浏览器自动化
  initBrowser: { argCount: 1 },
  clickElement: { argCount: 2 },
  fillField: { argCount: 3 },
  selectOption: { argCount: 2 },
  viewChanges: { argCount: 0 },
  getPageContent: { argCount: 0 },
  takeScreenshot: { argCount: 1 },
  closeBrowser: { argCount: 0 },
  searchOnPage: { argCount: 2 },
  findElements: { argCount: 2 },
  searchOnEngine: { argCount: 2 },
  downloadFile: { argCount: 3 },

  // 代码执行
  executeCode: { argCount: 2 },
  executeFile: { argCount: 2 },
  runJavaScript: { argCount: 1 },
  runPython: { argCount: 1 },
  formatCode: { argCount: 2 },

  // Git
  gitInit: { argCount: 1 },
  gitClone: { argCount: 3 },
  gitAdd: { argCount: 2 },
  gitCommit: { argCount: 2 },
  gitPush: { argCount: 3 },
  gitPull: { argCount: 3 },
  gitStatus: { argCount: 1 },
  gitLog: { argCount: 2 },
  gitBranchCreate: { argCount: 2 },
  gitBranchDelete: { argCount: 2 },
  gitBranchList: { argCount: 1 },
  gitCheckout: { argCount: 2 },
  gitCheckoutNew: { argCount: 2 },
  gitMerge: { argCount: 3 },
  gitDiff: { argCount: 2 },
  gitRemoteAdd: { argCount: 3 },
  gitRemoteList: { argCount: 1 },
  gitConfigUser: { argCount: 3 },
  gitReset: { argCount: 2 },
  gitStash: { argCount: 1 },
  gitStashPop: { argCount: 1 },

  // 任务管理
  createTask: { argCount: 4 },
  getTasks: { argCount: 0 },
  getTask: { argCount: 1 },
  updateTask: { argCount: 2 },
  deleteTask: { argCount: 1 },
  completeTask: { argCount: 1 },
  splitTask: { argCount: 2 },
  getTaskStats: { argCount: 0 },
  clearTasks: { argCount: 0 },

  // 记忆系统
  addMemory: { argCount: 3 },
  searchMemory: { argCount: 2 },
  getAllMemories: { argCount: 1 },
  getMemory: { argCount: 1 },
  updateMemory: { argCount: 2 },
  deleteMemory: { argCount: 1 },
  getMemoryStats: { argCount: 0 },
  getRelatedMemories: { argCount: 1 },
  clearMemory: { argCount: 0 },

  // 数据处理
  readCSV: { argCount: 1 },
  writeCSV: { argCount: 3 },
  readJSON: { argCount: 1 },
  writeJSON: { argCount: 2 },
  csvToJSON: { argCount: 2 },
  jsonToCSV: { argCount: 2 },
  queryData: { argCount: 2 },
  analyzeData: { argCount: 1 },
  sortData: { argCount: 3 },

  // 数据库
  executeSQL: { argCount: 2 },
  query: { argCount: 3 },
  insert: { argCount: 2 },
  update: { argCount: 3 },
  deleteData: { argCount: 2 },
  createTable: { argCount: 2 },
  dropTable: { argCount: 1 },
  getTables: { argCount: 0 },
  getTableSchema: { argCount: 1 },
  executeTransaction: { argCount: 1 },
  closeDB: { argCount: 0 },

  // 邮件
  sendEmail: { argCount: 4 },
  sendTextEmail: { argCount: 3 },
  sendHtmlEmail: { argCount: 3 },
  sendEmailWithAttachments: { argCount: 4 },
  sendTemplateEmail: { argCount: 3 },
  checkEmailConfig: { argCount: 0 },

  // 系统监控
  getCPUInfo: { argCount: 0 },
  getMemoryInfo: { argCount: 0 },
  getDiskInfo: { argCount: 0 },
  getNetworkInfo: { argCount: 0 },
  getProcesses: { argCount: 0 },
  getSystemInfo: { argCount: 0 },
  getCurrentProcess: { argCount: 0 },
  getSystemLoad: { argCount: 0 },
  monitorSystem: { argCount: 0 },
  formatBytes: { argCount: 1 },
  formatUptime: { argCount: 1 },

  // 定时任务
  addScheduleTask: { argCount: 4 },
  removeScheduleTask: { argCount: 1 },
  getScheduleTasks: { argCount: 0 },
  getScheduleTask: { argCount: 1 },
  updateScheduleTask: { argCount: 2 },
  toggleScheduleTask: { argCount: 1 },
  startScheduler: { argCount: 0 },
  stopScheduler: { argCount: 0 },

  // 存储
  createStorage: { argCount: 2 },

  // OCR 图像文字识别
  ocr: { argCount: 1 },
  ocrBatch: { argCount: 1 },

  // 视觉分析
  vision: { argCount: 2 },
  visionFromUrl: { argCount: 2 },

  // PPT 创建
  createPpt: { argCount: 1 },
  createWord: { argCount: 1 },
  createExcel: { argCount: 1 },
  readExcel: { argCount: 1 },

  // 集群管理
  spawnAgent: { argCount: 3 },
  delegateTask: { argCount: 2 },
  getClusterStatus: { argCount: 0 },
  stopAgent: { argCount: 1 },
  stopAllAgents: { argCount: 0 },
  parallelExecute: { argCount: 1 },
  getAgent: { argCount: 1 },
  panelDiscussion: { argCount: 2 },
  pipeline: { argCount: 1 },
  voting: { argCount: 2 },

  // 微信消息
  loginWechat: { argCount: 0 },
  logoutWechat: { argCount: 0 },
  sendWechatMessage: { argCount: 2 },
  sendWechatImage: { argCount: 2 },
  getWechatStatus: { argCount: 0 },
  generateWechatQRCode: { argCount: 0 },
};

// 导出工具元数据（供 registry.js 参考）
export { TOOL_METADATA };