import { getBasePath } from './path.ts';
import { ls, read, copy, mkdir, create } from './file.ts';
import { search, browse, fetchPage } from './web.ts';
import { listApps, openApp, closeApp } from './system.ts';
import {
  initBrowser,
  clickElement,
  fillField,
  selectOption,
  viewChanges,
  getPageContent,
  takeScreenshot,
  closeBrowser,
  searchOnPage,
  findElements,
  searchOnEngine,
  downloadFile,
} from './browser.ts';
import { executeCode, executeFile, runJavaScript, runPython, formatCode } from './code.ts';
import {
  gitInit,
  gitClone,
  gitAdd,
  gitCommit,
  gitPush,
  gitPull,
  gitStatus,
  gitLog,
  gitBranchCreate,
  gitBranchDelete,
  gitBranchList,
  gitCheckout,
  gitCheckoutNew,
  gitMerge,
  gitDiff,
  gitRemoteAdd,
  gitRemoteList,
  gitConfigUser,
  gitReset,
  gitStash,
  gitStashPop,
} from './git.ts';
import {
  createTask,
  getTasks,
  getTask,
  updateTask,
  deleteTask,
  completeTask,
  splitTask,
  getTaskStats,
  clearTasks,
} from './task.ts';
import {
  addMemory,
  searchMemory,
  getAllMemories,
  getMemory,
  updateMemory,
  deleteMemory,
  getMemoryStats,
  getRelatedMemories,
  clearMemory,
} from './memory.ts';
import {
  readCSV,
  writeCSV,
  readJSON,
  writeJSON,
  csvToJSON,
  jsonToCSV,
  queryData,
  analyzeData,
  sortData,
} from './data.ts';
import {
  executeSQL,
  query,
  insert,
  update,
  deleteData,
  createTable,
  dropTable,
  getTables,
  getTableSchema,
  executeTransaction,
  closeDB,
} from './db.ts';
import {
  sendEmail,
  sendTextEmail,
  sendHtmlEmail,
  sendEmailWithAttachments,
  sendTemplateEmail,
  checkEmailConfig,
} from './email.ts';
import {
  getCPUInfo,
  getMemoryInfo,
  getDiskInfo,
  getNetworkInfo,
  getProcesses,
  getSystemInfo,
  getCurrentProcess,
  getSystemLoad,
  monitorSystem,
  formatBytes,
  formatUptime,
} from './monitor.ts';
import {
  addScheduleTask,
  removeScheduleTask,
  getScheduleTasks,
  getScheduleTask,
  updateScheduleTask,
  toggleScheduleTask,
  startScheduler,
  stopScheduler,
} from './scheduler.ts';
import { FileStorage, createStorage } from './storage.ts';
import { ocr, ocrBatch } from './ocr.ts';
import { vision, visionFromUrl } from './vision.ts';
import { createPpt, createWord, createExcel, readExcel } from './office.ts';
import {
  isSandboxEnabled,
  createJavaScriptSandbox,
  runJavaScriptSandbox,
  runPythonSandbox,
  executeCodeSandbox,
} from './sandbox.ts';
import {
  spawnAgent,
  delegateTask,
  getClusterStatus,
  stopAgent,
  stopAllAgents,
  parallelExecute,
  getAgent,
  panelDiscussion,
  pipeline,
  voting,
} from './cluster.ts';
import {
  loginWechat,
  logoutWechat,
  startWechatPolling,
  stopWechatPolling,
  sendWechatMessage,
  sendWechatImage,
  getWechatStatus,
  generateWechatQRCode,
} from './wechat.ts';
import {
  convertCoord,
  calcDistance,
  calcArea,
  calcCenter,
  pointInPolygon,
  isInChina,
  readGeoJSON,
  queryGeoJSON,
  geoJSONStats,
  geoJSONToCSV,
  geoJSONToKML,
} from './gis.ts';
import {
  dnaComplement,
  dnaReverseComplement,
  rnaTranscribe,
  translate,
  gcContent,
  molecularWeight,
  hammingDistance,
  levenshteinDistance,
  tmEstimate,
  hairpinCheck,
  parseFASTA,
  parseFASTQ,
  fastaToCSV,
  codonUsage,
  randomSeq,
} from './bio.ts';
import {
  bmi,
  bsa,
  egfr,
  crcl,
  childPugh,
  calculateDose,
  bsaDose,
  infusionRate,
  idealBodyWeight,
  convertUnit,
  temperatureConvert,
  meanArterialPressure,
  anionGap,
  correctedCalcium,
  oxygenIndex,
  parseVitalSigns,
  vitalsReport,
} from './med.ts';
import {
  elementInfo,
  molWeight,
  elementComposition,
  molarity,
  dilution,
  phFromH,
  phToH,
  idealGasLaw,
  gasDensity,
} from './chem.ts';
import {
  compoundInterest,
  presentValue,
  futureValueAnnuity,
  npv,
  irr,
  paybackPeriod,
  roi,
  loanPayment,
  amortizationSchedule,
  totalInterest,
  movingAverage,
  volatility,
} from './finance.ts';
import {
  describe,
  correlation,
  linearRegression,
  matrixMultiply,
  matrixDeterminant,
  matrixInverse,
  solveQuadratic,
  factorial,
  combination,
  permutation,
  siConvert,
} from './math.ts';

export {
  getBasePath,
  ls,
  read,
  copy,
  mkdir,
  create,
  spawnAgent,
  delegateTask,
  getClusterStatus,
  stopAgent,
  stopAllAgents,
  parallelExecute,
  getAgent,
  panelDiscussion,
  pipeline,
  voting,
  search,
  browse,
  fetchPage,
  listApps,
  openApp,
  closeApp,
  initBrowser,
  clickElement,
  fillField,
  selectOption,
  viewChanges,
  getPageContent,
  takeScreenshot,
  closeBrowser,
  searchOnPage,
  findElements,
  searchOnEngine,
  downloadFile,
  executeCode,
  executeFile,
  runJavaScript,
  runPython,
  formatCode,
  gitInit,
  gitClone,
  gitAdd,
  gitCommit,
  gitPush,
  gitPull,
  gitStatus,
  gitLog,
  gitBranchCreate,
  gitBranchDelete,
  gitBranchList,
  gitCheckout,
  gitCheckoutNew,
  gitMerge,
  gitDiff,
  gitRemoteAdd,
  gitRemoteList,
  gitConfigUser,
  gitReset,
  gitStash,
  gitStashPop,
  createTask,
  getTasks,
  getTask,
  updateTask,
  deleteTask,
  completeTask,
  splitTask,
  getTaskStats,
  clearTasks,
  addMemory,
  searchMemory,
  getAllMemories,
  getMemory,
  updateMemory,
  deleteMemory,
  getMemoryStats,
  getRelatedMemories,
  clearMemory,
  readCSV,
  writeCSV,
  readJSON,
  writeJSON,
  csvToJSON,
  jsonToCSV,
  queryData,
  analyzeData,
  sortData,
  executeSQL,
  query,
  insert,
  update,
  deleteData,
  createTable,
  dropTable,
  getTables,
  getTableSchema,
  executeTransaction,
  closeDB,
  sendEmail,
  sendTextEmail,
  sendHtmlEmail,
  sendEmailWithAttachments,
  sendTemplateEmail,
  checkEmailConfig,
  getCPUInfo,
  getMemoryInfo,
  getDiskInfo,
  getNetworkInfo,
  getProcesses,
  getSystemInfo,
  getCurrentProcess,
  getSystemLoad,
  monitorSystem,
  formatBytes,
  formatUptime,
  addScheduleTask,
  removeScheduleTask,
  getScheduleTasks,
  getScheduleTask,
  updateScheduleTask,
  toggleScheduleTask,
  startScheduler,
  stopScheduler,
  FileStorage,
  createStorage,
  isSandboxEnabled,
  createJavaScriptSandbox,
  runJavaScriptSandbox,
  runPythonSandbox,
  executeCodeSandbox,
  ocr,
  ocrBatch,
  vision,
  visionFromUrl,
  createPpt,
  createWord,
  createExcel,
  readExcel,
  loginWechat,
  logoutWechat,
  startWechatPolling,
  stopWechatPolling,
  sendWechatMessage,
  sendWechatImage,
  getWechatStatus,
  generateWechatQRCode,
  convertCoord,
  calcDistance,
  calcArea,
  calcCenter,
  pointInPolygon,
  isInChina,
  readGeoJSON,
  queryGeoJSON,
  geoJSONStats,
  geoJSONToCSV,
  geoJSONToKML,
  dnaComplement,
  dnaReverseComplement,
  rnaTranscribe,
  translate,
  gcContent,
  molecularWeight,
  hammingDistance,
  levenshteinDistance,
  tmEstimate,
  hairpinCheck,
  parseFASTA,
  parseFASTQ,
  fastaToCSV,
  codonUsage,
  randomSeq,
  bmi,
  bsa,
  egfr,
  crcl,
  childPugh,
  calculateDose,
  bsaDose,
  infusionRate,
  idealBodyWeight,
  convertUnit,
  temperatureConvert,
  meanArterialPressure,
  anionGap,
  correctedCalcium,
  oxygenIndex,
  parseVitalSigns,
  vitalsReport,
  elementInfo,
  molWeight,
  elementComposition,
  molarity,
  dilution,
  phFromH,
  phToH,
  idealGasLaw,
  gasDensity,
  compoundInterest,
  presentValue,
  futureValueAnnuity,
  npv,
  irr,
  paybackPeriod,
  roi,
  loanPayment,
  amortizationSchedule,
  totalInterest,
  movingAverage,
  volatility,
  describe,
  correlation,
  linearRegression,
  matrixMultiply,
  matrixDeterminant,
  matrixInverse,
  solveQuadratic,
  factorial,
  combination,
  permutation,
  siConvert,
};
