# These are supported funding model platforms / 以下是支持的赞助平台
# You can enable one or more to accept donations from the community.
# 你可以启用一个或多个平台来接受社区捐赠。

github: [SnowLeopard-io] # Replace with your GitHub username / 替换为你的 GitHub 用户名


# patreon: # Uncomment to enable / 取消注释以启用
# open_collective: # Uncomment to enable / 取消注释以启用
# ko_fi: # Uncomment to enable / 取消注释以启用
# tidelift: # Uncomment to enable / 取消注释以启用
# community_bridge: # Uncomment to enable / 取消注释以启用
# liberapay: # Uncomment to enable / 取消注释以启用
# issuehunt: # Uncomment to enable / 取消注释以启用
# otechie: # Uncomment to enable / 取消注释以启用
# lfx_crowdfunding: # Uncomment to enable / 取消注释以启用
# custom: # Uncomment to add custom URLs / 取消注释以添加自定义链接
