version: '1.0'
name: CI
displayName: CI
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - project
        - develop
  pull_request:
    branches:
      prefix:
        - project
        - develop
stages:
  - stage: test
    id: test
    displayName: Test
    jobs:
      - job: test
        id: test
        displayName: Run tests
        steps:
          - step: npm_ci
            id: npm_ci
            name: Install dependencies
            script: npm ci
          - step: npm_test
            id: npm_test
            name: Run tests
            script: npm test
  - stage: build
    id: build
    displayName: Build
    jobs:
      - job: docker_build
        id: docker_build
        displayName: Build Docker
        steps:
          - step: docker_build
            id: docker_build_step
            name: Build Docker image
            script: docker build -t cogito-agent:${CI_COMMIT_SHA} .
